spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/subscription-db
    username: postgres
    password: webrise
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: default